--- #Create a new instance
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: True
  vars_files:
  - files/awscreds.yaml
  tasks:
  - name: Provisioning a t2.micro instance
    ec2:
      aws_access_key: '{{ aws_access }}'
      aws_secret_key: '{{ aws_secret }}'
      region: us-east-1
      image: ami-011b3ccf1bd6db744
      instance_type: t2.micro
      vpc_subnet_id: subnet-02d79aaeeb1ec6f58
      assign_public_ip: yes
      keypair: NewStart
      wait: yes
    register: ec2
  - name: Attach volume to instance
    ec2_vol:
      instance: '{{ item.id }}'
      device_name: /dev/xvdf
      region: us-east-1
      aws_access_key: '{{ aws_access }}'
      aws_secret_key: '{{ aws_secret }}'
      volume_size: 30
      volume_type: gp2
    with_items: '{{ ec2.instances }}'
    register: ec2_vol
